using System;
using System.Data;
using Oracle.ManagedDataAccess.Client; // Enterprise Oracle Data Provider
using Dapper;                          // Lightweight High-Performance Micro-ORM

namespace PaySphere.Gateway
{
    public class PaymentProcessor
    {
        private readonly string _connectionString;

        // Constructor accepting secure connection configuration injection
        public PaymentProcessor(string connectionString)
        {
            _connectionString = connectionString ?? throw new ArgumentNullException(nameof(connectionString));
        }

        /// <summary>
        /// Orchestrates an atomic funds transfer by executing the encapsulated Oracle PL/SQL package state.
        /// </summary>
        public TransactionResult ExecuteFundsTransfer(long sourceAccountId, long destinationAccountId, decimal amount, string reference)
        {
            // Defensive coding guard rails before contacting the data tier
            if (amount <= 0) return new TransactionResult(false, "System Rejection: Transfer amount must be positive.", null);
            if (sourceAccountId == destinationAccountId) return new TransactionResult(false, "System Rejection: Inter-account loops are prohibited.", null);

            // Establish secure connection boundaries via IDbConnection disposal patterns
            using (IDbConnection connection = new OracleConnection(_connectionString))
            {
                try
                {
                    connection.Open();

                    // Map parameterized inputs to matching PL/SQL Bind Variables (Mitigates SQL Injection completely)
                    var dbParameters = new DynamicParameters();
                    dbParameters.Add("p_source_acc_id", sourceAccountId, DbType.Int64, ParameterDirection.Input);
                    dbParameters.Add("p_dest_acc_id", destinationAccountId, DbType.Int64, ParameterDirection.Input);
                    dbParameters.Add("p_amount", amount, DbType.Decimal, ParameterDirection.Input);
                    dbParameters.Add("p_reference", reference, DbType.String, ParameterDirection.Input);
                    
                    // Captures the OUT parameter value assigned inside PKG_PAYMENT_PROCESSOR
                    dbParameters.Add("p_tx_id", dbType: DbType.Int64, direction: ParameterDirection.Output);

                    // Execute the Stored Procedure over Dapper using CommandType mapping
                    connection.Execute(
                        sql: "PKG_PAYMENT_PROCESSOR.PRC_TRANSFER_FUNDS",
                        param: dbParameters,
                        commandType: CommandType.StoredProcedure
                    );

                    // Fetch the resulting transactional block ID generated by the Oracle Identity Column
                    long generatedTxId = dbParameters.Get<long>("p_tx_id");

                    return new TransactionResult(true, "Transaction Processed Successfully.", generatedTxId);
                }
                catch (OracleException ex)
                {
                    // Intercept and parse custom application errors raised via Oracle RAISE_APPLICATION_ERROR
                    string technicalErrorMessage = $"Data Tier Exception [Error Code: {ex.Number}]: {ex.Message}";
                    return new TransactionResult(false, technicalErrorMessage, null);
                }
                catch (Exception ex)
                {
                    // Fallback for unexpected systemic or network failures
                    return new TransactionResult(false, $"Systemic Gateway Failure: {ex.Message}", null);
                }
            }
        }
    }

    // Explicit DTO to encapsulate transaction processing states back to API/UI components safely
    public class TransactionResult
    {
        public bool IsSuccessful { get; }
        public string Message { get; }
        public long? TransactionId { get; }

        public TransactionResult(bool success, string msg, long? txId)
        {
            IsSuccessful = success;
            Message = msg;
            TransactionId = txId;
        }
    }
}
